### ISSUE TITLE
[BUG] <title>Download error after upgrade to 2.1.0

### ISSUE THREAD

**Issue by Luisfelipeberchielli** [nathom/streamrip#828]
### Describe the bug

Download erro since upgraded to 2.1.0

### Command Used

```bash
C:\Users\Luis Felipe>rip url https://open.qobuz.com/album/bky7dwiqow2ac
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\rip\cli.py", line 16, in <module>
    from .config import Config
  File "C:\Program Files\Python312\Lib\site-packages\rip\config.py", line 13, in <module>
    from streamrip.exceptions import InvalidSourceError
ImportError: cannot import name 'InvalidSourceError' from 'streamrip.exceptions' (C:\Users\Luis Felipe\AppData\Roaming\Python\Python312\site-packages\streamrip\exceptions.py). Did you mean: 'InvalidAppIdError'?
```

### Debug Traceback

```text
C:\Users\Luis Felipe>rip url https://open.qobuz.com/album/bky7dwiqow2ac
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\rip\cli.py", line 16, in <module>
    from .config import Config
  File "C:\Program Files\Python312\Lib\site-packages\rip\config.py", line 13, in <module>
    from streamrip.exceptions import InvalidSourceError
ImportError: cannot import name 'InvalidSourceError' from 'streamrip.exceptions' (C:\Users\Luis Felipe\AppData\Roaming\Python\Python312\site-packages\streamrip\exceptions.py). Did you mean: 'InvalidAppIdError'?
```

### Config File

```toml
C:\Users\Luis Felipe>rip config open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\rip.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\rip\cli.py", line 16, in <module>
    from .config import Config
  File "C:\Program Files\Python312\Lib\site-packages\rip\config.py", line 13, in <module>
    from streamrip.exceptions import InvalidSourceError
ImportError: cannot import name 'InvalidSourceError' from 'streamrip.exceptions' (C:\Users\Luis Felipe\AppData\Roaming\Python\Python312\site-packages\streamrip\exceptions.py). Did you mean: 'InvalidAppIdError'?
```

### Operating System

windows 11

### streamrip version

2.1.0

**Comment by Luisfelipeberchielli** [comment]
Solved using ChatGPT

**Comment by Louis2530** [comment]
Nice, can you close this issue ?
